.\" Manpage for wg.
.\" Contact contact.scottforsberg@gmail.com.
.TH man 8 "06 Jun 2019" ".3" "wg man page"
.SH NAME
wg \- create a new word 
.SH SYNOPSIS
wg [ -l parameter ] [ -w parameter ] [-r ] [ -v ]
.SH DESCRIPTION
This program generates words of various lengths and composition. Types include randomly generated words, and compound words made op of smaller terms.
.SH OPTIONS
-l 	set number of letters per word 5-7
	default is 6

-w 	set number of words to generate, default is 1

-r	use real words, combinations of 3 and 4 letter random words

-v 	enables verbose output

-? 	display options
.SH SEE ALSO
wg-domain-check() 
.SH BUGS
No known bugs.
.SH AUTHOR
Scott Forsberg (contact.scottforsberg@gmail.com)
